<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-09 at 09:38:58.
 */
namespace Tests;

use ElKuKu\Crowdin\Crowdin;

class CrowdinTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var Crowdin
	 */
	protected $object;

	/**
	 * @covers ElKuKu\Crowdin\Crowdin::__construct
	 */
	public function test()
	{
		$this->assertThat(
			$this->object,
			$this->isInstanceOf('ElKuKu\Crowdin\Crowdin')
		);

	}

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new Crowdin('x', 'y');
	}

	/**
	 * @covers ElKuKu\Crowdin\Crowdin::__get
	 */
	public function test__get()
	{
		$this->assertThat(
			$this->object->file,
			$this->isInstanceOf('ElKuKu\Crowdin\Package\File')
		);
	}

	/**
	 * @covers ElKuKu\Crowdin\Crowdin::__get
	 * @expectedException  \InvalidArgumentException
	 */
	public function test__getException()
	{
		$this->object->invalid;
	}
}
