<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-09 at 12:33:29.
 */
namespace Tests;

use ElKuKu\Crowdin\Package\Language;
use Tests\Fake\FakeClient;

class LanguageTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var Language
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new Language('{projectID}', '{APIKey}', new FakeClient);
	}

	/**
	 * @covers ElKuKu\Crowdin\Package\Language::getSupported
	 * @todo   Implement testGetSupported().
	 */
	public function testGetSupported()
	{
		$this->assertThat(
			$this->object->getSupported(),
			$this->equalTo(
				'supported-languages'
			)
		);
	}

	/**
	 * @covers ElKuKu\Crowdin\Package\Language::getStatus
	 * @todo   Implement testGetStatus().
	 */
	public function testGetStatus()
	{
		$this->assertThat(
			$this->object->getStatus('{language}'),
			$this->equalTo(
				'project/{projectID}/language-status?key={APIKey}&form_params%5Blanguage%5D=%7Blanguage%7D'
			)
		);
	}
}
