<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-09 at 09:53:25.
 */
namespace Tests;

use ElKuKu\Crowdin\Languagefile;

class LanguagefileTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var Languagefile
	 */
	protected $object;

	protected $dataDir = '';

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->dataDir = __DIR__ . '/Data';

		$this->object = new Languagefile($this->dataDir . '/test.txt', 'path/at/crowdin/test.txt');
	}

	/**
	 * @expectedException  \InvalidArgumentException
	 * 
	 */
	public function test()
	{
		new Languagefile('invalid/path', 'path/at/crowdin/test.txt');
	}


	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @covers ElKuKu\Crowdin\Languagefile::getLocalPath
	 * @todo   Implement testGetLocalPath().
	 */
	public function testGetLocalPath()
	{
		$this->assertThat(
			$this->object->getLocalPath(),
			$this->equalTo($this->dataDir . '/test.txt')
		);
	}

	/**
	 * @covers ElKuKu\Crowdin\Languagefile::getCrowdinPath
	 * @todo   Implement testGetCrowdinPath().
	 */
	public function testGetCrowdinPath()
	{
		$this->assertThat(
			$this->object->getCrowdinPath(),
			$this->equalTo('path/at/crowdin/test.txt')
		);
	}

	/**
	 * @covers ElKuKu\Crowdin\Languagefile::setExportPattern
	 * @todo   Implement testSetExportPattern().
	 */
	public function testSetExportPattern()
	{
		$this->object->setExportPattern('fooBar');

		$this->assertThat(
			$this->object->getExportPattern(),
			$this->equalTo('fooBar')
		);
	}

	/**
	 * @covers ElKuKu\Crowdin\Languagefile::getExportPattern
	 * @todo   Implement testGetExportPattern().
	 */
	public function testGetExportPattern()
	{
		$this->object->setExportPattern('fooBar');

		$this->assertThat(
			$this->object->getExportPattern(),
			$this->equalTo('fooBar')
		);
	}

	/**
	 * @covers ElKuKu\Crowdin\Languagefile::setTitle
	 * @todo   Implement testSetTitle().
	 */
	public function testSetTitle()
	{
		$this->object->setTitle('fooBar');

		$this->assertThat(
			$this->object->getTitle(),
			$this->equalTo('fooBar')
		);
	}

	/**
	 * @covers ElKuKu\Crowdin\Languagefile::getTitle
	 * @todo   Implement testGetTitle().
	 */
	public function testGetTitle()
	{
		$this->object->setTitle('fooBar');

		$this->assertThat(
			$this->object->getTitle(),
			$this->equalTo('fooBar')
		);
	}
}
