<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-09 at 12:10:16.
 */
namespace Tests;

use ElKuKu\Crowdin\Package\Memory;
use Tests\Fake\FakeClient;

class MemoryTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var Memory
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new Memory('{projectID}', '{APIKey}', new FakeClient);
	}

	/**
	 * @covers ElKuKu\Crowdin\Package\Memory::download
	 * @todo   Implement testDownload().
	 */
	public function testDownload()
	{
		$this->assertThat(
			$this->object->download(),
			$this->equalTo('project/{projectID}/download-tm?key={APIKey}&include_assigned=1')
		);
	}

	/**
	 * @covers ElKuKu\Crowdin\Package\Memory::upload
	 * @todo   Implement testUpload().
	 */
	public function testUpload()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet (since it does a REAL request...)'
		);

		return;

		$this->assertThat(
			$this->object->upload(__DIR__ . '/Data/test.txt'),
			$this->equalTo('')
		);
	}

	/**
	 * @covers ElKuKu\Crowdin\Package\Glossary::upload
	 * @expectedException  \UnexpectedValueException
	 */
	public function testUploadException()
	{
		$this->object->upload('/file/not/found');
	}
}
