<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-09 at 10:14:26.
 */
namespace Tests;

use Tests\Fake\FakeClient;
use Tests\Fake\FakePackage;

class PackageTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var FakePackage
     */
    protected $object;

	/**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    	$this->object = new FakePackage('foo', 'bar', new FakeClient);
    }

	public function testGetProjectId()
	{
		$this->assertThat(
			$this->object->testGetProjectId(),
			$this->equalTo('foo')
		);
	}

	public function testGetApiKey()
	{
		$this->assertThat(
			$this->object->testGetApiKey(),
			$this->equalTo('bar')
		);
	}

	public function testGetBasePath()
	{
		$this->assertThat(
			$this->object->testGetBasePath('foo'),
			$this->equalTo('project/foo/foo?key=bar')
		);
	}

	public function testGetHttpClient()
	{
		$this->assertThat(
			$this->object->testGetHttpClient(),
			$this->isInstanceOf('Tests\Fake\FakeClient')
		);
	}
}
