<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-09 at 12:38:37.
 */
namespace Tests;

use ElKuKu\Crowdin\Package\Project;
use Tests\Fake\FakeClient;

class ProjectTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var Project
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new Project('{projectID}', '{APIKey}', new FakeClient);
	}

	/**
	 * @covers ElKuKu\Crowdin\Package\Project::getInfo
	 * @todo   Implement testGetInfo().
	 */
	public function testGetInfo()
	{
		$this->assertThat(
			$this->object->getInfo(),
			$this->equalTo(
				'project/{projectID}/info?key={APIKey}'
			)
		);
	}

	/**
	 * @covers ElKuKu\Crowdin\Package\Project::delete
	 * @todo   Implement testDelete().
	 */
	public function testDelete()
	{
		$this->assertThat(
			$this->object->delete(),
			$this->equalTo(
				'project/{projectID}/delete-project?key={APIKey}'
			)
		);
	}
}
